import type { Metadata } from "next";
import { Bebas_Neue, Manrope, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { CustomCursor } from "@/components/Cursor";

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: ["400"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebas.variable} ${manrope.variable} ${grotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CustomCursor />
        <div className="pointer-events-none fixed inset-0 opacity-[0.125] mix-blend-soft-light bg-[url('/noise3.png')] bg-repeat z-50" />

        {children}
      </body>
    </html>
  );
}
